[package]
name = "nmea_codec"
version = "0.1.0"
edition = "2024"

[dependencies]
ais_types = { version="0.1.0", path = "../ais_rs/ais_types" }
ais_asm = { version="0.1.0", path = "../ais_rs/ais_asm" }
ais_message = { version="0.1.0", path = "../ais_rs/ais_message" }

tokio-util = { version = "0.7.18", features = ["codec"] }
futures = "0.3.32"
chrono = "0.4.45"
uom = "0.38.0"
bytes = "1.12.1"
show-option = "0.2.0"
lazy_format = "2.0.3"
bitvec = "1"
deku = "0.20.3"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["full"] }
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
